### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by schristley** [TACC-Cloud/tapis-cli#335]
**Describe the bug**
Get the following error during installation:

```
Collecting petname>=2.6 (from agavepy>=1.0.0a8->-r requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/8e/a5/348c90b3fb09d7bd76f7dacf1b92e251d75bfbe715006cb9b84eb23be1b1/petname-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_rtt71eu/petname/setup.py", line 23, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
```

**To Reproduce**
```
$ git clone https://github.com/TACC-Cloud/tapis-cli.git
$ cd tapis-cli
$ pip install --upgrade .
```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 18.04

**Additional context**
Trying to install within a docker

**Comment by mwvaughn** [comment]
Can you post the contents of your Dockerfile here to help diagnose the issue?

**Comment by schristley** [comment]
```
FROM ubuntu:18.04

LABEL maintainer="iReceptorPlus"

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --fix-missing \
    git \
    python3 \
    python3-pip \
    python3-sphinx \
    python3-scipy \
    libyaml-dev \
    r-base \
    r-base-dev \
    wget \
    curl

RUN pip3 install \
    pandas \
    biopython \
    matplotlib \
    airr \
    presto \
    changeo

# Tapis CLI
RUN cd / && git clone https://github.com/TACC-Cloud/tapis-cli.git
ENV PATH "/tapis-cli/bin:${PATH}"
RUN cd /tapis-cli && pip3 install -r requirements.txt

# Copy source
RUN mkdir /irplus-tapis
COPY . /irplus-tapis
```

Looking further, It looks to the `petname` python package which agavepy uses. I get the same error when trying to install it directly.

```
root@8ed630b51dd3:/tapis-cli# pip3 install petname
Collecting petname
  Downloading https://files.pythonhosted.org/packages/8e/a5/348c90b3fb09d7bd76f7dacf1b92e251d75bfbe715006cb9b84eb23be1b1/petname-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ahsh1i5c/petname/setup.py", line 23, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
```

**Comment by schristley** [comment]
All foiled by some non-ASCII characters in petname's README...

**Comment by schristley** [comment]
filed [issue](https://github.com/dustinkirkland/python-petname/issues/11) with petname, and hacked around it with this:

```
RUN git clone https://github.com/dustinkirkland/python-petname
RUN cd /python-petname && echo "" > README.md && python3 setup.py install
```

**Comment by schristley** [comment]
Allows for install but then cannot get past `tapis auth init`, do I need to use python2?

```
root@3cf4ae06d22d:/# tapis auth init --interactive
Configure Tapis API access:
Enter a tenant name [tacc.prod]: vdjserver.org
vdjserver.org username: schristley
vdjserver.org password for schristley: 
'ascii' codec can't decode byte 0xe2 in position 8993: ordinal not in range(128)
```

**Comment by schristley** [comment]
I moved up to ubuntu: 20.04, the same as in the tapis-cli docker, and that seems to have resolved the issues. Not sure if that will cause conflicts with my other tools but we'll see.
